/**
 * The theme keys in an object format.
 * ALL CREATED, PUBLICLY-FACING VARIABLES MUST BE RECORDED HERE
 */

export type StratumTheme = typeof emptyTheme;

export const emptyTheme = {
  base: {
    "--base-text-scaling": "",
    "--base-font-color": "",
    "--base-font-color-dark": "",
    "--base-background-color": "",
    "--base-background-color-dark": "",
    "--base-font-family": "",
    "--base-font-size": "",
    "--base-line-height": "",
    "--base-font-weight": "",
    "--base-font-style": "",
    "--base-letter-spacing": "",
  },
  presets: {
    shared: {
      "--radius-preset-base": "",
    },
    typography: {
      anchor: {
        "--color-preset-anchor-light": "",
        "--color-preset-anchor-dark": "",
        "--font-preset-anchor": "",
        "--font-weight-preset-anchor": "",
        "--style-preset-anchor": "",
        "--tracking-preset-anchor": "",
      },
      heading: {
        "--color-preset-heading-light": "",
        "--color-preset-heading-dark": "",
        "--font-preset-heading": "",
        "--font-weight-preset-heading": "",
        "--style-preset-heading": "",
        "--tracking-preset-heading": "",
      },
    },
  },
  colors: {
    main: {
      primary: {
        "--color-primary-50": "",
        "--color-primary-100": "",
        "--color-primary-200": "",
        "--color-primary-300": "",
        "--color-primary-400": "",
        "--color-primary-500": "",
        "--color-primary-600": "",
        "--color-primary-700": "",
        "--color-primary-800": "",
        "--color-primary-900": "",
        "--color-primary-950": "",
      },
      secondary: {
        "--color-secondary-50": "",
        "--color-secondary-100": "",
        "--color-secondary-200": "",
        "--color-secondary-300": "",
        "--color-secondary-400": "",
        "--color-secondary-500": "",
        "--color-secondary-600": "",
        "--color-secondary-700": "",
        "--color-secondary-800": "",
        "--color-secondary-900": "",
        "--color-secondary-950": "",
      },
      tertiary: {
        "--color-tertiary-50": "",
        "--color-tertiary-100": "",
        "--color-tertiary-200": "",
        "--color-tertiary-300": "",
        "--color-tertiary-400": "",
        "--color-tertiary-500": "",
        "--color-tertiary-600": "",
        "--color-tertiary-700": "",
        "--color-tertiary-800": "",
        "--color-tertiary-900": "",
        "--color-tertiary-950": "",
      },
      success: {
        "--color-success-50": "",
        "--color-success-100": "",
        "--color-success-200": "",
        "--color-success-300": "",
        "--color-success-400": "",
        "--color-success-500": "",
        "--color-success-600": "",
        "--color-success-700": "",
        "--color-success-800": "",
        "--color-success-900": "",
        "--color-success-950": "",
      },
      warning: {
        "--color-warning-50": "",
        "--color-warning-100": "",
        "--color-warning-200": "",
        "--color-warning-300": "",
        "--color-warning-400": "",
        "--color-warning-500": "",
        "--color-warning-600": "",
        "--color-warning-700": "",
        "--color-warning-800": "",
        "--color-warning-900": "",
        "--color-warning-950": "",
      },
      error: {
        "--color-error-50": "",
        "--color-error-100": "",
        "--color-error-200": "",
        "--color-error-300": "",
        "--color-error-400": "",
        "--color-error-500": "",
        "--color-error-600": "",
        "--color-error-700": "",
        "--color-error-800": "",
        "--color-error-900": "",
        "--color-error-950": "",
      },
      surface: {
        "--color-surface-50": "",
        "--color-surface-100": "",
        "--color-surface-200": "",
        "--color-surface-300": "",
        "--color-surface-400": "",
        "--color-surface-500": "",
        "--color-surface-600": "",
        "--color-surface-700": "",
        "--color-surface-800": "",
        "--color-surface-900": "",
        "--color-surface-950": "",
      },
    },
    contrasts: {
      primary: {
        "--color-contrast-primary-50": "",
        "--color-contrast-primary-100": "",
        "--color-contrast-primary-200": "",
        "--color-contrast-primary-300": "",
        "--color-contrast-primary-400": "",
        "--color-contrast-primary-500": "",
        "--color-contrast-primary-600": "",
        "--color-contrast-primary-700": "",
        "--color-contrast-primary-800": "",
        "--color-contrast-primary-900": "",
        "--color-contrast-primary-950": "",
      },
      secondary: {
        "--color-contrast-secondary-50": "",
        "--color-contrast-secondary-100": "",
        "--color-contrast-secondary-200": "",
        "--color-contrast-secondary-300": "",
        "--color-contrast-secondary-400": "",
        "--color-contrast-secondary-500": "",
        "--color-contrast-secondary-600": "",
        "--color-contrast-secondary-700": "",
        "--color-contrast-secondary-800": "",
        "--color-contrast-secondary-900": "",
        "--color-contrast-secondary-950": "",
      },
      tertiary: {
        "--color-contrast-tertiary-50": "",
        "--color-contrast-tertiary-100": "",
        "--color-contrast-tertiary-200": "",
        "--color-contrast-tertiary-300": "",
        "--color-contrast-tertiary-400": "",
        "--color-contrast-tertiary-500": "",
        "--color-contrast-tertiary-600": "",
        "--color-contrast-tertiary-700": "",
        "--color-contrast-tertiary-800": "",
        "--color-contrast-tertiary-900": "",
        "--color-contrast-tertiary-950": "",
      },
      success: {
        "--color-contrast-success-50": "",
        "--color-contrast-success-100": "",
        "--color-contrast-success-200": "",
        "--color-contrast-success-300": "",
        "--color-contrast-success-400": "",
        "--color-contrast-success-500": "",
        "--color-contrast-success-600": "",
        "--color-contrast-success-700": "",
        "--color-contrast-success-800": "",
        "--color-contrast-success-900": "",
        "--color-contrast-success-950": "",
      },
      warning: {
        "--color-contrast-warning-50": "",
        "--color-contrast-warning-100": "",
        "--color-contrast-warning-200": "",
        "--color-contrast-warning-300": "",
        "--color-contrast-warning-400": "",
        "--color-contrast-warning-500": "",
        "--color-contrast-warning-600": "",
        "--color-contrast-warning-700": "",
        "--color-contrast-warning-800": "",
        "--color-contrast-warning-900": "",
        "--color-contrast-warning-950": "",
      },
      error: {
        "--color-contrast-error-50": "",
        "--color-contrast-error-100": "",
        "--color-contrast-error-200": "",
        "--color-contrast-error-300": "",
        "--color-contrast-error-400": "",
        "--color-contrast-error-500": "",
        "--color-contrast-error-600": "",
        "--color-contrast-error-700": "",
        "--color-contrast-error-800": "",
        "--color-contrast-error-900": "",
        "--color-contrast-error-950": "",
      },
      surface: {
        "--color-contrast-surface-50": "",
        "--color-contrast-surface-100": "",
        "--color-contrast-surface-200": "",
        "--color-contrast-surface-300": "",
        "--color-contrast-surface-400": "",
        "--color-contrast-surface-500": "",
        "--color-contrast-surface-600": "",
        "--color-contrast-surface-700": "",
        "--color-contrast-surface-800": "",
        "--color-contrast-surface-900": "",
        "--color-contrast-surface-950": "",
      },
    }
  },
};