export const stratumThemeKeys = [
  "--base-font-color",
  "--base-font-color-dark",
  "--base-background-color",
  "--base-background-color-dark",
  "--base-font-family",
  "--base-font-size",
  "--base-line-height",
  "--base-font-weight",
  "--base-font-style",
  "--base-letter-spacing",

  "--radius-preset-base",

  "--color-preset-anchor-light",
  "--color-preset-anchor-dark",
  "--font-preset-anchor",
  "--font-weight-preset-anchor",
  "--style-preset-anchor",
  "--tracking-preset-anchor",

  "--color-preset-heading-light",
  "--color-preset-heading-dark",
  "--font-preset-heading",
  "--font-weight-preset-heading",
  "--style-preset-heading",
  "--tracking-preset-heading",

  // Primary
  "--color-primary-50",
  "--color-primary-100",
  "--color-primary-200",
  "--color-primary-300",
  "--color-primary-400",
  "--color-primary-500",
  "--color-primary-600",
  "--color-primary-700",
  "--color-primary-800",
  "--color-primary-900",
  "--color-primary-950",

  // Secondary
  "--color-secondary-50",
  "--color-secondary-100",
  "--color-secondary-200",
  "--color-secondary-300",
  "--color-secondary-400",
  "--color-secondary-500",
  "--color-secondary-600",
  "--color-secondary-700",
  "--color-secondary-800",
  "--color-secondary-900",
  "--color-secondary-950",

  // Tertiary
  "--color-tertiary-50",
  "--color-tertiary-100",
  "--color-tertiary-200",
  "--color-tertiary-300",
  "--color-tertiary-400",
  "--color-tertiary-500",
  "--color-tertiary-600",
  "--color-tertiary-700",
  "--color-tertiary-800",
  "--color-tertiary-900",
  "--color-tertiary-950",

  // Success
  "--color-success-50",
  "--color-success-100",
  "--color-success-200",
  "--color-success-300",
  "--color-success-400",
  "--color-success-500",
  "--color-success-600",
  "--color-success-700",
  "--color-success-800",
  "--color-success-900",
  "--color-success-950",

  // Warning
  "--color-warning-50",
  "--color-warning-100",
  "--color-warning-200",
  "--color-warning-300",
  "--color-warning-400",
  "--color-warning-500",
  "--color-warning-600",
  "--color-warning-700",
  "--color-warning-800",
  "--color-warning-900",
  "--color-warning-950",

  // Error
  "--color-error-50",
  "--color-error-100",
  "--color-error-200",
  "--color-error-300",
  "--color-error-400",
  "--color-error-500",
  "--color-error-600",
  "--color-error-700",
  "--color-error-800",
  "--color-error-900",
  "--color-error-950",

  // Surface
  "--color-surface-50",
  "--color-surface-100",
  "--color-surface-200",
  "--color-surface-300",
  "--color-surface-400",
  "--color-surface-500",
  "--color-surface-600",
  "--color-surface-700",
  "--color-surface-800",
  "--color-surface-900",
  "--color-surface-950",
] as const;

export const stratumStaticThemeKeys = [
  "--base-font-color",
  "--base-font-dark",
  "--base-background-color",
  "--base-background-dark",
  "--base-font-family",
  "--base-font-size",
  "--base-line-height",
  "--base-font-weight",
  "--base-font-style",
  "--base-letter-spacing",

  "--radius-preset-base",

  "--preset-anchor-light",
  "--preset-anchor-dark",
  "--font-preset-anchor",
  "--font-weight-preset-anchor",
  "--style-preset-anchor",
  "--tracking-preset-anchor",

  "--preset-heading-light",
  "--preset-heading-dark",
  "--font-preset-heading",
  "--font-weight-preset-heading",
  "--style-preset-heading",
  "--tracking-preset-heading",

  // Primary
  "--primary-50",
  "--primary-100",
  "--primary-200",
  "--primary-300",
  "--primary-400",
  "--primary-500",
  "--primary-600",
  "--primary-700",
  "--primary-800",
  "--primary-900",
  "--primary-950",

  // Secondary
  "--secondary-50",
  "--secondary-100",
  "--secondary-200",
  "--secondary-300",
  "--secondary-400",
  "--secondary-500",
  "--secondary-600",
  "--secondary-700",
  "--secondary-800",
  "--secondary-900",
  "--secondary-950",

  // Tertiary
  "--tertiary-50",
  "--tertiary-100",
  "--tertiary-200",
  "--tertiary-300",
  "--tertiary-400",
  "--tertiary-500",
  "--tertiary-600",
  "--tertiary-700",
  "--tertiary-800",
  "--tertiary-900",
  "--tertiary-950",

  // Success
  "--success-50",
  "--success-100",
  "--success-200",
  "--success-300",
  "--success-400",
  "--success-500",
  "--success-600",
  "--success-700",
  "--success-800",
  "--success-900",
  "--success-950",

  // Warning
  "--warning-50",
  "--warning-100",
  "--warning-200",
  "--warning-300",
  "--warning-400",
  "--warning-500",
  "--warning-600",
  "--warning-700",
  "--warning-800",
  "--warning-900",
  "--warning-950",

  // Error
  "--error-50",
  "--error-100",
  "--error-200",
  "--error-300",
  "--error-400",
  "--error-500",
  "--error-600",
  "--error-700",
  "--error-800",
  "--error-900",
  "--error-950",

  // Surface
  "--surface-50",
  "--surface-100",
  "--surface-200",
  "--surface-300",
  "--surface-400",
  "--surface-500",
  "--surface-600",
  "--surface-700",
  "--surface-800",
  "--surface-900",
  "--surface-950",
] as const;
